index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]

# XSS
xss-home:
    uri: /xss
    controller: Controller\Xss\HomeController
    httpMethod: [GET]
xss-discover:
    uri: /xss/discover
    controller: Controller\Xss\DiscoverController
    httpMethod: [GET]
xss-stored:
    uri: /xss/stored
    controller: Controller\Xss\StoredController
    httpMethod: [GET,POST]
xss-reflected:
    uri: /xss/reflected
    controller: Controller\Xss\ReflectedController
    httpMethod: [GET]
xss-blind:
    uri: /xss/blind
    controller: Controller\Xss\BlindController
    httpMethod: [GET,POST]
xss-blind-target:
    uri: /xss/blind/target
    controller: Controller\Xss\BlindTargetController
    httpMethod: [GET]

# COMMAND INJECTION
command-injection:
    uri: /command-injection
    controller: Controller\CommandInjection\HomeController
    httpMethod: [GET]
command-injection-discover:
    uri: /command-injection/discover
    controller: Controller\CommandInjection\DiscoverController
    httpMethod: [GET,POST]
command-injection-exploit:
    uri: /command-injection/exploit
    controller: Controller\CommandInjection\ExploitController
    httpMethod: [GET,POST]

# SQL INJECTION
sql-injection:
    uri: /sql-injection
    controller: Controller\SqlInjection\HomeController
    httpMethod: [GET]
sql-injection-discover:
    uri: /sql-injection/discover
    controller: Controller\SqlInjection\DiscoverController
    httpMethod: [GET,POST]
sql-injection-auth-bypass:
    uri: /sql-injection/auth-bypass
    controller: Controller\SqlInjection\AuthBypassController
    httpMethod: [GET,POST]
sql-injection-blind:
    uri: /sql-injection/blind
    controller: Controller\SqlInjection\BlindAttackController
    httpMethod: [GET,POST]

# TOOLS
testdb:
    uri: /tools/testdb
    controller: Controller\Tools\DataBaseTestController
    httpMethod: [GET]
truncate-comments:
    uri: /tools/truncate/comments
    controller: Controller\Tools\TruncateCommentTableController
    httpMethod: [GET]
truncate-tickets:
    uri: /tools/truncate/tickets
    controller: Controller\Tools\TruncateTicketTableController
    httpMethod: [GET]
