index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]
xss:
    uri: /xss
    controller: Controller\XssController
    httpMethod: [GET]
testdb:
    uri: /testdb
    controller: Controller\DataBaseTestController
    httpMethod: [GET]